query subjectMarks($key: String!, $subject: String!) {
  user(key: $key) {
    id
    subjectMarks(subject: $subject) {
      id
      name
      mark
      date
      value {
        NAZEV
      }
    }
  }
}
