query calendarDay($key: String!, $date: String!) {
  user(key: $key) {
    id
    calendarDay(date: $date) {
      id
      name
      teacher
      timeFrom
      timeTo
      class
      type
      order
      color
      notes {
        note
        order
      }
    }
  }
}
